version: '3'

services:
  products_web:
    build: ./products
    volumes:
      - .:./code
    ports:
      - 8001:8001

  emails_web:
    build: ./emails
    volumes:
      - .:./code
    ports:
      - 8002:8002

  orders_web:
    build: ./orders
    volumes:
      - .:./code
    ports:
      - 8003:8003

  mongod:
    image: mongod:3.4.7
    ports:
      - 27017:27017
    command: mongod